repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: check-executables-have-shebangs

      - id: check-toml
      - id: check-yaml

      - id: flake8
        files: 'badgerer_api/|tests/|e2e_tests/'
      - id: check-ast
      - id: debug-statements
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
      - id: mypy
        files: 'badgerer_api/|tests/|e2e_tests/'
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: "python3.7"
        files: 'badgerer_api/|tests/|e2e_tests/'
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 4.0.1
    hooks:
      - id: pydocstyle
        files: badgerer_api/
